
m4_include(`preclude.m4')

m4_include_w4(`preamble.f')

m4_require_w4(`std/compile.f')
m4_require_w4(`std/constants.f')
m4_require_w4(`std/constants-create.f')
m4_require_w4(`std/constants-structs.f')
m4_require_w4(`std/control.f')
m4_require_w4(`std/dictionary.f')
m4_require_w4(`std/environment.f')
m4_require_w4(`std/exceptions.f')
m4_require_w4(`std/file.f')
m4_require_w4(`std/locals.f')
m4_require_w4(`std/logic.f')
m4_require_w4(`std/logic-number.f')
m4_require_w4(`std/math.f')
m4_require_w4(`std/math-double.f')
m4_require_w4(`std/memory.f')
m4_require_w4(`std/parse.f')
m4_require_w4(`std/parse-file.f')
m4_require_w4(`std/search.f')
m4_require_w4(`std/search-string.f')
m4_require_w4(`std/stack.f')
m4_require_w4(`std/stack-control.f')
m4_require_w4(`std/stack-ptr.f')
m4_require_w4(`std/stdio.f')
m4_require_w4(`std/string.f')
m4_require_w4(`std/string-utils.f')
m4_require_w4(`std/structs.f')
m4_require_w4(`std/test.f')
m4_require_w4(`std/text.f')
m4_require_w4(`std/value.f')

m4_require_w4(`ext/debug.f')
m4_require_w4(`ext/hash.f')
m4_require_w4(`ext/is.f')
m4_require_w4(`ext/list.f')
m4_require_w4(`ext/unimplemented.f')
m4_require_w4(`ext/wasi.f')
