
m4_changequote(<!,!>)

m4_include(<!scripts/preclude.m4!>)

m4_include(<!preamble.f!>)

m4_require(<!std/compile.f!>)
m4_require(<!std/constants.f!>)
m4_require(<!std/constants-create.f!>)
m4_require(<!std/constants-structs.f!>)
m4_require(<!std/control.f!>)
m4_require(<!std/environment.f!>)
m4_require(<!std/exceptions.f!>)
m4_require(<!std/file.f!>)
m4_require(<!std/interpret.f!>)
m4_require(<!std/locals.f!>)
m4_require(<!std/logic.f!>)
m4_require(<!std/logic-base.f!>)
m4_require(<!std/logic-number.f!>)
m4_require(<!std/math.f!>)
m4_require(<!std/math-double.f!>)
m4_require(<!std/memory.f!>)
m4_require(<!std/parse.f!>)
m4_require(<!std/parse-file.f!>)
m4_require(<!std/parse-source.f!>)
m4_require(<!std/search.f!>)
m4_require(<!std/stack.f!>)
m4_require(<!std/stack-base.f!>)
m4_require(<!std/stack-control.f!>)
m4_require(<!std/stack-cs.f!>)
m4_require(<!std/stack-rs.f!>)
m4_require(<!std/stack-ptr.f!>)
m4_require(<!std/stdio.f!>)
m4_require(<!std/string.f!>)
m4_require(<!std/string-escape.f!>)
m4_require(<!std/string-format.f!>)
m4_require(<!std/string-search.f!>)
m4_require(<!std/string-utils.f!>)
m4_require(<!std/structs.f!>)
m4_require(<!std/test.f!>)
m4_require(<!std/value.f!>)

m4_require(<!ext/debug.f!>)
m4_require(<!ext/hash.f!>)
m4_require(<!ext/is.f!>)
m4_require(<!ext/list.f!>)
m4_require(<!ext/wasi.f!>)
