
m4_include(`preclude.m4')
m4_include(`preamble.f')

m4_require(`std/constants.f')
m4_require(`std/compile.f')
m4_require(`std/dictionary.f')
m4_require(`std/environment.f')
m4_require(`std/exceptions.f')
m4_require(`std/locals.f')
m4_require(`std/logic.f')
m4_require(`std/logic.number.f')
m4_require(`std/loops.f')
m4_require(`std/math.f')
m4_require(`std/math.double.f')
m4_require(`std/memory.f')
m4_require(`std/parse.f')
m4_require(`std/search.f')
m4_require(`std/search.string.f')
m4_require(`std/stack.f')
m4_require(`std/stack.loop.f')
m4_require(`std/stack.ptr.f')
m4_require(`std/stdio.f')
m4_require(`std/string.f')
m4_require(`std/string.utils.f')
m4_require(`std/structs.f')
m4_require(`std/test.f')
m4_require(`std/text.f')
m4_require(`std/value.f')

m4_require(`ext/debug.f')
m4_require(`ext/hash.f')
m4_require(`ext/is.f')
m4_require(`ext/list.f')
m4_require(`ext/unimplemented.f')
m4_require(`ext/wasi.f')
